---
- name: Operations on VMs
  community.general.proxmox_kvm:
     acpi: "{{ item['acpi'] if item.get('acpi') else global['acpi'] }}"
     agent: "{{ item['agent'] if item.get('agent') else ( global['agent'] if global['agent'] else omit ) }}"
     api_host: "{{ item['api_host'] if item.get('api_host') else ( global['api_host'] if global['api_host'] else omit ) }}"
     api_password: "{{ item['api_password'] if item.get('api_password') else ( global['api_password'] if global['api_password'] else omit ) }}"
     api_user: "{{ item['api_user'] if item.get('api_user') else ( global['api_user'] if global['api_user'] else omit ) }}"
     args: "{{ item['args'] if item.get('args') else ( global['args'] if global['args'] else omit ) }}"
     autostart: "{{ item['autostart'] if item.get('autostart') else global['autostart'] }}"
     balloon: "{{ item['balloon'] if item.get('balloon') else global['balloon'] }}"
     bios: "{{ item['bios'] if item.get('bios') else ( global['bios'] if global['bios'] else omit ) }}"
     boot: "{{ item['boot'] if item.get('boot') else global['boot'] }}"
     bootdisk: "{{ item['bootdisk'] if item.get('bootdisk') else ( global['bootdisk'] if global['bootdisk'] else omit ) }}"
     clone: "{{ item['clone'] if item.get('clone') else ( global['clone'] if global['clone'] else omit ) }}"
     cores: "{{ item['cores'] if item.get('cores') else global['cores'] }}"
     cpu: "{{ item['cpu'] if item.get('cpu') else global['cpu'] }}"
     cpulimit: "{{ item['cpulimit'] if item.get('cpulimit') else ( global['cpulimit'] if global['cpulimit'] else omit ) }}"
     cpuunits: "{{ item['cpuunits'] if item.get('cpuunits') else global['cpuunits'] }}"
     delete: "{{ item['delete'] if item.get('delete') else ( global['delete'] if global['delete'] else omit ) }}"
     description: "{{ item['description'] if item.get('description') else ( global['description'] if global['description'] else omit ) }}"
     digest: "{{ item['digest'] if item.get('digest') else ( global['digest'] if global['digest'] else omit ) }}"
     force: "{{ item['force'] if item.get('force') else ( global['force'] if global['force'] else omit ) }}"
     format: "{{ item['format'] if item.get('format') else global['format'] }}"
     freeze: "{{ item['freeze'] if item.get('freeze') else ( global['freeze'] if global['freeze'] else omit ) }}"
     full: "{{ item['full'] if item.get('full') else ( global['full'] if global['full'] else omit ) }}"
     hostpci: "{{ item['hostpci'] if item.get('hostpci') else ( global['hostpci'] if global['hostpci'] else omit ) }}"
     hotplug: "{{ item['hotplug'] if item.get('hotplug') else ( global['hotplug'] if global['hotplug'] else omit ) }}"
     hugepages: "{{ item['hugepages'] if item.get('hugepages') else ( global['hugepages'] if global['hugepages'] else omit ) }}"
     ide: "{{ item['ide'] if item.get('ide') else ( global['ide'] if global['ide'] else omit ) }}"
     keyboard: "{{ item['keyboard'] if item.get('keyboard') else ( global['keyboard'] if global['keyboard'] else omit ) }}"
     kvm: "{{ item['kvm'] if item.get('kvm') else global['kvm'] }}"
     localtime: "{{ item['localtime'] if item.get('localtime') else ( global['localtime'] if global['localtime'] else omit ) }}"
     lock: "{{ item['lock'] if item.get('lock') else ( global['lock'] if global['lock'] else omit ) }}"
     machine: "{{ item['machine'] if item.get('machine') else ( global['machine'] if global['machine'] else omit ) }}"
     memory: "{{ item['memory'] if item.get('memory') else global['memory'] }}"
     migrate_downtime: "{{ item['migrate_downtime'] if item.get('migrate_downtime') else ( global['migrate_downtime'] if global['migrate_downtime'] else omit ) }}"
     migrate_speed: "{{ item['migrate_speed'] if item.get('migrate_speed') else ( global['migrate_speed'] if global['migrate_speed'] else omit ) }}"
     name: "{{ item['name'] if item.get('name') else ( global['name'] if global['name'] else omit ) }}"
     net: "{{ item['net'] if item.get('net') else ( global['net'] if global['net'] else omit ) }}"
     newid: "{{ item['newid'] if item.get('newid') else ( global['newid'] if global['newid'] else omit ) }}"
     node: "{{ item['node'] if item.get('node') else ( global['node'] if global['node'] else omit ) }}"
     numa: "{{ item['numa'] if item.get('numa') else ( global['numa'] if global['numa'] else omit ) }}"
     numa_enabled: "{{ item['numa_enabled'] if item.get('numa_enabled') else ( global['numa_enabled'] if global['numa_enabled'] else omit ) }}"
     onboot: "{{ item['onboot'] if item.get('onboot') else global['onboot'] }}"
     ostype: "{{ item['ostype'] if item.get('ostype') else global['ostype'] }}"
     parallel: "{{ item['parallel'] if item.get('parallel') else ( global['parallel'] if global['parallel'] else omit ) }}"
     pool: "{{ item['pool'] if item.get('pool') else ( global['pool'] if global['pool'] else omit ) }}"
     protection: "{{ item['protection'] if item.get('protection') else ( global['protection'] if global['protection'] else omit ) }}"
     proxmox_default_behavior: "{{ item['proxmox_default_behavior'] if item.get('proxmox_default_behavior') else global['proxmox_default_behavior'] }}"
     reboot: "{{ item['reboot'] if item.get('reboot') else ( global['reboot'] if global['reboot'] else omit ) }}"
     revert: "{{ item['revert'] if item.get('revert') else ( global['revert'] if global['revert'] else omit ) }}"
     sata: "{{ item['sata'] if item.get('sata') else ( global['sata'] if global['sata'] else omit ) }}"
     scsi: "{{ item['scsi'] if item.get('scsi') else ( global['scsi'] if global['scsi'] else omit ) }}"
     scsihw: "{{ item['scsihw'] if item.get('scsihw') else ( global['scsihw'] if global['scsihw'] else omit ) }}"
     serial: "{{ item['serial'] if item.get('serial') else ( global['serial'] if global['serial'] else omit ) }}"
     shares: "{{ item['shares'] if item.get('shares') else ( global['shares'] if global['shares'] else omit ) }}"
     skiplock: "{{ item['skiplock'] if item.get('skiplock') else ( global['skiplock'] if global['skiplock'] else omit ) }}"
     smbios: "{{ item['smbios'] if item.get('smbios') else ( global['smbios'] if global['smbios'] else omit ) }}"
     snapname: "{{ item['snapname'] if item.get('snapname') else ( global['snapname'] if global['snapname'] else omit ) }}"
     sockets: "{{ item['sockets'] if item.get('sockets') else global['sockets'] }}"
     startdate: "{{ item['startdate'] if item.get('startdate') else ( global['startdate'] if global['startdate'] else omit ) }}"
     startup: "{{ item['startup'] if item.get('startup') else ( global['startup'] if global['startup'] else omit ) }}"
     state: "{{ operation | default('current') }}"
     storage: "{{ item['storage'] if item.get('storage') else ( global['storage'] if global['storage'] else omit ) }}"
     tablet: "{{ item['tablet'] if item.get('tablet') else global['tablet'] }}"
     target: "{{ item['target'] if item.get('target') else ( global['target'] if global['target'] else omit ) }}"
     tdf: "{{ item['tdf'] if item.get('tdf') else ( global['tdf'] if global['tdf'] else omit ) }}"
     template: "{{ item['template'] if item.get('template') else global['template'] }}"
     timeout: "{{ item['timeout'] if item.get('timeout') else ( global['timeout'] if global['timeout'] else omit ) }}"
     update: "{{ update if update is defined else (item['update'] if item.get('update') else ( global['update'] if global['update'] else omit )) }}"
     validate_certs: "{{ item['validate_certs'] if item.get('validate_certs') else ( global['validate_certs'] if global['validate_certs'] else omit ) }}"
     vcpus: "{{ item['vcpus'] if item.get('vcpus') else ( global['vcpus'] if global['vcpus'] else omit ) }}"
     vga: "{{ item['vga'] if item.get('vga') else global['vga'] }}"
     virtio: "{{ item['virtio'] if item.get('virtio') else ( global['virtio'] if global['virtio'] else omit ) }}"
     vmid: "{{ item['vmid'] if item.get('vmid') else ( global['vmid'] if global['vmid'] else omit ) }}"
     watchdog: "{{ item['watchdog'] if item.get('watchdog') else ( global['watchdog'] if global['watchdog'] else omit ) }}"
  delegate_to: localhost
  with_items: "{{ vm_list | default([]) }}"
